### ISSUE TITLE
Error message from scWGNA.report()

### ISSUE THREAD

**Issue by phoebee-h** [CFeregrino/scWGCNA#2]
Hi, 
I'm looking forward to your R package! Thanks for the development! 
First, I follow the instruction, but the error shows as below when running "scWGNA.report()"
```
 # Calculate pseudocells
ps.pbmc_small=calculate.pseudocells(Seurat::pbmc_small, dims = 1:10)
gnames= data.frame(a=as.character(rownames(ps.pbmc_small))); gnames[,2]=gnames[,1]

# Use pseudocells and single cells to calculate WGCNA
scWGNA.report(data = ps.pbmc_small,sc.data = Seurat::pbmc_small, gene.names = gnames, project.name = "test", sp="Hs")
```

```
Quitting from lines 206-394 (scWGCNA_report.Rmd)
Error in data.frame(i, j, dim(z), names(z[1]), unname(z[1])) :
  arguments imply differing number of rows: 1, 0
```

Then, with my own data set, here shows another error message
```
Quitting from lines 418-433 (scWGCNA_report.Rmd)
Error in data.frame(p.Wdata@reductions[[my.dr]]@cell.embeddings) :
  trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots
```

I don't know what to check exactly. In my own dataset, I'm sure that "cell.embeddings" exists.
![image](https://user-images.githubusercontent.com/28743573/108583281-6225a680-7373-11eb-8a30-1e4bc3b11c3b.png)

Thanks so much.
Phoebe.

**Comment by CFeregrino** [comment]
Hello!
Thanks for trying to use the package, and for sending me this error!
I'm new at building packages altogether, so you might need some patience before this works 100%

There is a new version of the package, which should be more functional now. Please try again if you have time and let me know how it goes.
Also, make sure that your Seurat object has a "tsne" reduction, or change the reduction argument in the function if you want to use something else.

Thanks!

**Comment by phoebee-h** [comment]
Hi, 

Here shows another error, was it a problem for missing libraries? I assume only "Seurat" and "scWGCNA" are required?

```
# Calculate pseudocells
ps.pbmc_small=calculate.pseudocells(Seurat::pbmc_small, dims = 1:10)
gnames= data.frame(a=as.character(rownames(ps.pbmc_small))); gnames[,2]=gnames[,1]

# Use pseudocells and single cells to calculate WGCNA
scWGNA.report(data = ps.pbmc_small,sc.data = Seurat::pbmc_small, gene.names = gnames, project.name = "test", sp="Hs")
```

```
Quitting from lines 525-589 (scWGCNA_report.Rmd)
Error in as.environment(where) :
  S4 object does not extend class "environment"
```

And "tsne" reduction is included (just for cheking).
![image](https://user-images.githubusercontent.com/28743573/108973570-747b4980-76bf-11eb-8605-53d159faf4d4.png)

Thank you.

**Comment by safabio** [comment]
Hi Phoebe,
So the pbmc_small data set you are using consists of only 80 cells and 230 genes. The pipeline is not designed to handle such small data sets. 

I tried to run it with your code, but I was not able to recreate the errors. The pipeline terminates way earlier at the soft threshold picking. The scale free topology values reached are to small to ensure WGCNA to run properly. 

Maybe try with the full pbmc data set and you should not get those errors.

Fabio

**Comment by phoebee-h** [comment]
Hi Fabio,
Indeed. Using another file (17949 genes, 1114 cells) and uncomment the lines in the script (as you replied here: https://github.com/CFeregrino/scWGCNA/issues/4#issuecomment-804721360), it works now. 

Thank you.
